import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {createHash} from 'node:crypto';
import {recoverCollectionDivergence} from '../src/services/collectionGitRecovery.js';
import {captureContains} from '../src/services/captureCoverage.js';
import {enqueuePublication,CLOUD_QUEUE_PATH} from '../src/services/cloudPublication.js';
const exec=promisify(execFile);
test('divergent generated data is archived before replay, while remote changes and local evidence survive',async t=>{
  const dir=await fs.mkdtemp(path.join(os.tmpdir(),'collection-git-'));
  t.after(()=>fs.rm(dir,{recursive:true,force:true}));
  const local=path.join(dir,'local'),remote=path.join(dir,'remote.git'),other=path.join(dir,'other'),stateDir=path.join(dir,'private');
  const gitAt=cwd=>async args=>(await exec('git',['-c','user.name=Test','-c','user.email=test@example.invalid',...args],{cwd,windowsHide:true})).stdout;
  const parent=gitAt(dir);await parent(['init','--bare','--initial-branch=master',remote]);await parent(['clone',remote,local]);
  const git=gitAt(local);await fs.mkdir(path.join(local,'data/collection-workflow'),{recursive:true});
  await fs.writeFile(path.join(local,CLOUD_QUEUE_PATH),JSON.stringify({schema_version:1,requests:[]}));
  await git(['add','.']);await git(['commit','-m','initial']);await git(['push','origin','master']);
  await parent(['clone',remote,other]);
  const id='11111111-1111-4111-8111-111111111111',publicationId='22222222-2222-4222-8222-222222222222';
  const data={kind:'paper_project',workflow_run_id:id,catalog:{pages:[]},records:[]},text=JSON.stringify(data)+'\n';
  const hash=createHash('sha256').update(text).digest('hex');
  await fs.mkdir(path.join(stateDir,id),{recursive:true});await fs.writeFile(path.join(stateDir,id,'export.json'),text);
  await fs.writeFile(path.join(stateDir,id,'run.json'),JSON.stringify({run:{id},export_hash:hash,phase:'failed',failed_stage:'uploading',failures:6}));
  await enqueuePublication(local,{id,publicationId,inputHash:hash,paperIds:[]});
  await git(['add','.']);await git(['commit','-m','data: save browser collection and workflow receipts']);
  const original=(await git(['rev-parse','HEAD'])).trim();
  const cloud=gitAt(other);await fs.writeFile(path.join(other,'cloud.txt'),'remote translation saved');
  await cloud(['add','.']);await cloud(['commit','-m','cloud translation']);await cloud(['push','origin','master']);await git(['fetch','origin']);
  const options={git,stateDir,allowedFiles:new Set([CLOUD_QUEUE_PATH])};
  await fs.writeFile(path.join(local,'user.txt'),'unsaved user work');
  await assert.rejects(recoverCollectionDivergence(options),/干净/);assert.equal((await git(['rev-parse','HEAD'])).trim(),original);
  await fs.unlink(path.join(local,'user.txt'));
  const proof=path.join(stateDir,id,'export.json');await fs.rename(proof,proof+'.saved');
  await assert.rejects(recoverCollectionDivergence(options));assert.equal((await git(['rev-parse','HEAD'])).trim(),original);
  await fs.rename(proof+'.saved',proof);
  await assert.rejects(recoverCollectionDivergence({...options,allowedFiles:new Set()}),/非采集/);
  assert.deepEqual(await recoverCollectionDivergence(options),[id]);
  assert.equal((await git(['rev-parse','refs/heads/codex/collection-recovery-'+original])).trim(),original);
  assert.equal(await fs.readFile(path.join(local,'cloud.txt'),'utf8'),'remote translation saved');
  assert.equal(await fs.readFile(proof,'utf8'),text);
  const replay=JSON.parse(await fs.readFile(path.join(stateDir,id,'run.json'),'utf8'));
  assert.equal(replay.phase,'ready');assert.equal(replay.failures,0);assert.equal(replay.recovery_from,original);
  assert.equal((await git(['rev-parse','HEAD'])).trim(),(await cloud(['rev-parse','HEAD'])).trim());
});
test('only a superset of exact frozen captures can supersede pending batches',()=>{
  const a={parent_run_id:'parent',records:[{doi:'one',evidence:'original'}],catalog:{pages:[{id:'page',items:[1]}]},ai_review_results:{a:{verdict:'confirmed'}},catalog_review_results:{}};
  const b=structuredClone(a);b.records.push({doi:'two',evidence:'second'});b.ai_review_results.b={verdict:'confirmed'};
  assert.equal(captureContains(b,a),true);assert.equal(captureContains(a,b),false);
  b.records[0].evidence='changed';assert.equal(captureContains(b,a),false);
  b.records[0]=a.records[0];b.ai_review_results.a.verdict='failed';assert.equal(captureContains(b,a),false);
  assert.equal(captureContains({...a,parent_run_id:'another'},a),false);
});
